// Shared in-memory store for mock mode (no DB)
export const mockComplaints = [
  {
    _id: 'demo-001',
    caseId: 'CX360-2025-0321-1001',
    source: 'email',
    rawMessage: 'I was charged twice for the same UPI transaction on March 15th. Transaction ID: TXN-78234. The duplicate debit of ₹14,999 appeared on my savings account. I need an immediate reversal. This is affecting my account balance and I have EMI payments due tomorrow.',
    customerName: 'Rajesh Kumar',
    customerId: 'CUS-1001',
    customerContact: 'rajesh.kumar@email.com',
    category: 'Transaction Issue',
    sentiment: 'Negative',
    priority: 'High',
    severityScore: 7,
    confidence: 92,
    status: 'classified',
    shouldEscalate: false,
    regulatoryFlag: 'None',
    slaStatus: 'within',
    aiReply: 'Dear Rajesh Kumar,\n\nThank you for bringing this billing discrepancy to our attention. Your complaint has been registered with reference number CX360-2025-0321-1001.\n\nI sincerely apologize for the duplicate debit of ₹14,999 on your savings account. I have escalated your case (Transaction ID: TXN-78234) to our transaction processing department for immediate reversal.\n\nYou can expect the refund within 3-5 business days. Given your upcoming EMI payment, I have also flagged your account to prevent any overdraft charges.\n\nPlease don\'t hesitate to reach out if you need further assistance.\n\nBest regards,\nCX360 Banking Support Team',
    suggestedAction: 'Initiate transaction reversal through core banking system. Flag account for EMI protection.',
    processedAt: new Date(Date.now() - 2 * 3600000),
    createdAt: new Date(Date.now() - 2 * 3600000),
    updatedAt: new Date(Date.now() - 2 * 3600000),
  },
  {
    _id: 'demo-002',
    caseId: 'CX360-2025-0321-1002',
    source: 'whatsapp',
    rawMessage: 'Someone made unauthorized transactions on my credit card. Three purchases totaling ₹85,000 were made from an online store I never visited. I have my card with me and didn\'t share my OTP with anyone. This is fraud! I want to file an FIR and complain to RBI if not resolved immediately.',
    customerName: 'Priya Sharma',
    customerId: 'CUS-2034',
    customerContact: '+91-9876543210',
    category: 'Fraud & Dispute',
    sentiment: 'Negative',
    priority: 'Urgent',
    severityScore: 9,
    confidence: 96,
    status: 'escalated',
    shouldEscalate: true,
    escalatedTo: 'Fraud Team',
    escalationReason: 'Fraud & Dispute category with unauthorized transaction report and RBI mention',
    regulatoryFlag: 'RBI',
    regulatoryReason: 'Customer mentioned RBI complaint escalation',
    slaStatus: 'within',
    aiReply: 'Dear Priya Sharma,\n\nThis is an urgent priority case. Your complaint has been registered with reference number CX360-2025-0321-1002.\n\nI understand the severity of unauthorized transactions totaling ₹85,000 on your credit card. We take fraud cases extremely seriously.\n\nImmediate actions taken:\n1. Your credit card has been temporarily blocked to prevent further unauthorized use\n2. A fraud investigation team has been assigned to your case\n3. Dispute charges have been initiated for all three transactions\n\nPlease visit your nearest branch with a valid ID to complete the dispute documentation. You may also file an FIR at your local police station.\n\nAs per RBI guidelines, you are protected under the zero-liability framework for unauthorized transactions reported within 3 days.\n\nBest regards,\nCX360 Fraud Investigation Team',
    suggestedAction: 'URGENT: Route to Fraud Investigation team immediately. Block card, initiate chargeback process. RBI compliance flag raised.',
    processedAt: new Date(Date.now() - 1 * 3600000),
    createdAt: new Date(Date.now() - 1 * 3600000),
    updatedAt: new Date(Date.now() - 1 * 3600000),
  },
  {
    _id: 'demo-003',
    caseId: 'CX360-2025-0321-1003',
    source: 'webform',
    rawMessage: 'My home loan application has been pending for over 45 days now. Application number HL-2025-4521. I submitted all required documents including income proof, property papers, and KYC documents. Nobody from the loan department is responding to my calls. This delay is causing me to lose the property deal.',
    customerName: 'Amit Patel',
    customerContact: 'amit.patel@outlook.com',
    category: 'Loan & EMI',
    sentiment: 'Negative',
    priority: 'High',
    severityScore: 7,
    confidence: 91,
    status: 'classified',
    shouldEscalate: false,
    regulatoryFlag: 'None',
    slaStatus: 'approaching',
    aiReply: 'Dear Amit Patel,\n\nThank you for your patience regarding your home loan application (HL-2025-4521). Your complaint has been registered with reference number CX360-2025-0321-1003.\n\nI sincerely apologize for the extended processing time. I have escalated your application to our loan processing manager for priority review.\n\nI will personally ensure you receive a status update within 48 hours with a clear timeline for approval/disbursement.\n\nBest regards,\nCX360 Banking Support Team',
    suggestedAction: 'Contact loan processing department. Escalate to loan manager. Provide customer with direct contact number.',
    processedAt: new Date(Date.now() - 8 * 3600000),
    createdAt: new Date(Date.now() - 8 * 3600000),
    updatedAt: new Date(Date.now() - 8 * 3600000),
  },
  {
    _id: 'demo-004',
    caseId: 'CX360-2025-0321-1004',
    source: 'phone',
    rawMessage: 'ATM at MG Road branch dispensed only ₹5,000 instead of ₹20,000 but my account was debited for the full amount. ATM ID: ATM-BLR-0042. This happened at 3:45 PM today. I need the remaining ₹15,000 credited back to my account immediately.',
    customerName: 'Suresh Reddy',
    customerContact: '+91-8765432109',
    category: 'Branch & ATM',
    sentiment: 'Negative',
    priority: 'High',
    severityScore: 7,
    confidence: 93,
    status: 'classified',
    shouldEscalate: false,
    regulatoryFlag: 'None',
    slaStatus: 'within',
    aiReply: 'Dear Suresh Reddy,\n\nYour complaint has been registered with reference number CX360-2025-0321-1004.\n\nI apologize for the ATM cash dispensing issue at our MG Road branch (ATM-BLR-0042). I have initiated an investigation.\n\nPer RBI guidelines, ATM-related disputes are resolved within 5 working days. We will verify the ATM journal and CCTV footage. If the discrepancy is confirmed, ₹15,000 will be credited to your account.\n\nBest regards,\nCX360 Banking Support Team',
    suggestedAction: 'Raise ATM dispute ticket. Request ATM journal from ATM ops team. Timeline: 5 working days as per RBI guidelines.',
    processedAt: new Date(Date.now() - 5 * 3600000),
    createdAt: new Date(Date.now() - 5 * 3600000),
    updatedAt: new Date(Date.now() - 5 * 3600000),
  },
  {
    _id: 'demo-005',
    caseId: 'CX360-2025-0321-1005',
    source: 'chat',
    rawMessage: 'I cannot login to my net banking account. It shows "Account Locked" after I entered wrong password 3 times. I need urgent access as I have to make a NEFT transfer today before 5 PM for a business payment.',
    customerName: 'Deepika Nair',
    customerContact: 'deepika.nair@gmail.com',
    category: 'Net Banking / App',
    sentiment: 'Negative',
    priority: 'Medium',
    severityScore: 5,
    confidence: 89,
    status: 'classified',
    shouldEscalate: false,
    regulatoryFlag: 'None',
    slaStatus: 'within',
    aiReply: 'Dear Deepika Nair,\n\nYour complaint has been registered with reference number CX360-2025-0321-1005.\n\nI understand the urgency of your NEFT transfer. Your net banking account has been locked as a security measure after multiple incorrect password attempts.\n\nTo reset your access:\n1. Visit the "Forgot Password" page on our net banking portal\n2. Enter your registered mobile number for OTP verification\n3. Set a new password\n\nIf you\'re unable to reset online, please call our 24/7 helpline at 1800-XXX-XXXX for immediate assistance.\n\nBest regards,\nCX360 Banking Support Team',
    suggestedAction: 'Guide customer through password reset. If unable, unlock account from admin panel.',
    processedAt: new Date(Date.now() - 3 * 3600000),
    createdAt: new Date(Date.now() - 3 * 3600000),
    updatedAt: new Date(Date.now() - 3 * 3600000),
  },
  {
    _id: 'demo-006',
    caseId: 'CX360-2025-0321-1006',
    source: 'email',
    rawMessage: 'I was charged ₹2,500 as account maintenance fee which was not disclosed when I opened my savings account. Also, there is a ₹500 charge for SMS alerts that I never opted for. I want a complete refund of these hidden charges. If not resolved, I will escalate to the banking ombudsman.',
    customerName: 'Kavita Joshi',
    customerId: 'CUS-3412',
    customerContact: 'kavita.joshi@email.com',
    category: 'Interest & Charges',
    sentiment: 'Negative',
    priority: 'High',
    severityScore: 6,
    confidence: 88,
    status: 'classified',
    shouldEscalate: false,
    regulatoryFlag: 'RBI',
    regulatoryReason: 'Customer mentioned banking ombudsman escalation',
    slaStatus: 'within',
    aiReply: 'Dear Kavita Joshi,\n\nYour complaint has been registered with reference number CX360-2025-0321-1006.\n\nI apologize for the inconvenience caused by the unexpected charges. I have reviewed your account and initiated the following:\n\n1. ₹2,500 account maintenance fee — under review for possible reversal\n2. ₹500 SMS alert charges — reversal initiated as you did not opt for this service\n\nYou will receive a resolution within 7 working days.\n\nBest regards,\nCX360 Banking Support Team',
    suggestedAction: 'Review account opening documents for fee disclosure. Reverse SMS charges immediately. Escalate maintenance fee to branch manager.',
    processedAt: new Date(Date.now() - 12 * 3600000),
    createdAt: new Date(Date.now() - 12 * 3600000),
    updatedAt: new Date(Date.now() - 12 * 3600000),
  },
  {
    _id: 'demo-007',
    caseId: 'CX360-2025-0321-1007',
    source: 'manual',
    rawMessage: 'Customer walked in to report that their new debit card ordered 3 weeks ago has not been delivered. Card number ending 4589. The old card expired on March 1st and customer has no card access currently. Requests urgent card issuance.',
    customerName: 'Vikram Singh',
    customerId: 'CUS-5567',
    customerContact: '+91-7654321098',
    category: 'Card Services',
    sentiment: 'Negative',
    priority: 'Medium',
    severityScore: 5,
    confidence: 90,
    status: 'classified',
    shouldEscalate: false,
    regulatoryFlag: 'None',
    slaStatus: 'breached',
    aiReply: 'Dear Vikram Singh,\n\nYour complaint has been registered with reference number CX360-2025-0321-1007.\n\nI apologize for the delay in delivering your replacement debit card. I have initiated an express re-issuance of your card.\n\nAs an interim measure, we can issue you a temporary card at your nearest branch. Please visit with a valid government ID.\n\nThe new card will be delivered within 3-5 business days via speed post.\n\nBest regards,\nCX360 Banking Support Team',
    suggestedAction: 'Track card dispatch status. If lost in transit, issue replacement with express delivery. Offer branch-issued temporary card.',
    processedAt: new Date(Date.now() - 72 * 3600000),
    createdAt: new Date(Date.now() - 72 * 3600000),
    updatedAt: new Date(Date.now() - 72 * 3600000),
  },
  {
    _id: 'demo-008',
    caseId: 'CX360-2025-0321-1008',
    source: 'webform',
    rawMessage: 'I am extremely satisfied with how quickly your team resolved my credit card billing dispute last week. Special thanks to agent Meera who followed up daily until the refund was processed. Excellent customer service!',
    customerName: 'Arjun Mehta',
    customerContact: 'arjun.mehta@company.co',
    category: 'General',
    sentiment: 'Positive',
    priority: 'Low',
    severityScore: 1,
    confidence: 97,
    status: 'resolved',
    shouldEscalate: false,
    regulatoryFlag: 'None',
    slaStatus: 'within',
    resolutionNote: 'Positive feedback acknowledged and shared with team.',
    resolvedAt: new Date(Date.now() - 20 * 3600000),
    aiReply: 'Dear Arjun Mehta,\n\nThank you so much for your kind feedback! We are delighted to hear about your positive experience with our support team.\n\nI will personally ensure Meera receives this recognition. Your feedback motivates our entire team to maintain the highest standards of service.\n\nWe truly value your relationship with us.\n\nWarm regards,\nCX360 Banking Support Team',
    suggestedAction: 'Forward positive feedback to agent Meera and her supervisor. Log for monthly performance review.',
    processedAt: new Date(Date.now() - 24 * 3600000),
    createdAt: new Date(Date.now() - 24 * 3600000),
    updatedAt: new Date(Date.now() - 24 * 3600000),
  },
];
