export const mockComplaints = [
  {
    id: 'C-2024-001',
    customer: 'John Smith',
    email: 'john.smith@email.com',
    channel: 'Email',
    description: 'I was charged twice for the same transaction on my credit card. This is unacceptable! I need an immediate refund.',
    category: 'Billing',
    sentiment: 'Negative',
    severity: 'High',
    status: 'Open',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    sla_deadline: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'C-2024-002',
    customer: 'Sarah Johnson',
    email: 'sarah.j@email.com',
    channel: 'Chat',
    description: 'The product I ordered arrived damaged. The box was crushed and the item inside is broken. I need a replacement urgently.',
    category: 'Product Quality',
    sentiment: 'Negative',
    severity: 'Medium',
    status: 'In Progress',
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    sla_deadline: new Date(Date.now() + 19 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'C-2024-003',
    customer: 'Mike Chen',
    email: 'mike.chen@email.com',
    channel: 'Phone',
    description: 'Great service! The delivery was on time and the product quality exceeded my expectations. Thank you!',
    category: 'Service',
    sentiment: 'Positive',
    severity: 'Low',
    status: 'Resolved',
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    sla_deadline: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'C-2024-004',
    customer: 'Emily Davis',
    email: 'emily.d@email.com',
    channel: 'Web',
    description: 'My package has been stuck in transit for 5 days. The tracking shows no updates. Where is my order?',
    category: 'Delivery',
    sentiment: 'Negative',
    severity: 'High',
    status: 'Open',
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    sla_deadline: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'C-2024-005',
    customer: 'Robert Wilson',
    email: 'robert.w@email.com',
    channel: 'Email',
    description: 'The app keeps crashing whenever I try to make a payment. I have tried reinstalling but the issue persists.',
    category: 'Technical Support',
    sentiment: 'Negative',
    severity: 'Medium',
    status: 'In Progress',
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    sla_deadline: new Date(Date.now() + 21 * 60 * 60 * 1000).toISOString(),
  },
];

export const kpiData = {
  totalComplaints: 1247,
  slaCompliance: 94.8,
  avgResolutionTime: '18.5h',
  customerSatisfaction: 4.2,
};

export const chartData = {
  volumeTrend: [
    { date: 'Jan 01', complaints: 45 },
    { date: 'Jan 02', complaints: 52 },
    { date: 'Jan 03', complaints: 48 },
    { date: 'Jan 04', complaints: 61 },
    { date: 'Jan 05', complaints: 55 },
    { date: 'Jan 06', complaints: 67 },
    { date: 'Jan 07', complaints: 58 },
  ],
  categoryDistribution: [
    { category: 'Billing', count: 342, percentage: 27.4 },
    { category: 'Product Quality', count: 298, percentage: 23.9 },
    { category: 'Delivery', count: 256, percentage: 20.5 },
    { category: 'Technical Support', count: 189, percentage: 15.2 },
    { category: 'Service', count: 162, percentage: 13.0 },
  ],
};
